config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    put 'hide', on: :member
    get 'search', on: :collection
  end
  resource :session, only: %i[new create destroy]
  resources :users, except: %i[index], param: :nickname
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  REGEXP = /#[[[:word:]]-]+/

  scope :question_hashtags_only, -> { joins(:hashtag_questions).distinct }

  has_many :hashtag_questions
  has_many :questions, through: :hashtag_questions

  validates :name, uniqueness: true
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question, optional: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions

  validates :body, presence: true, length: { maximum: 280 }

  after_save_commit :create_hashtags

  private

  def create_hashtags
    self.hashtags =
      "#{body} #{answer}"
      .downcase
      .scan(Hashtag::REGEXP)
      .uniq
      .map { |hashtag| Hashtag.find_or_create_by(name: hashtag.delete('#')) }
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  has_secure_password

  VALID_EMAIL_REGEXP = /\A[a-z\d_+.-]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
  VALID_NAVBAR_COLOR_REGEXP = /\A\#\h{3}{1,2}\z/
  VALID_NICKNAME_REGEXP = /\A\w+\z/

  has_many :questions, dependent: :delete_all
  has_many :authored_questions, class_name: 'Question', foreign_key: 'author_id',
                                dependent: :nullify

  before_validation :downcase_email
  before_validation :downcase_nickname

  validates :email, presence: true, uniqueness: true,
                    format: { with: VALID_EMAIL_REGEXP }
  validates :navbar_color, format: { with: VALID_NAVBAR_COLOR_REGEXP }
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 },
                       format: { with: VALID_NICKNAME_REGEXP }

  gravtastic(secure: true, filetype: :png, size: 100, default: 'mm')

  def to_param
    nickname
  end

  private

  def downcase_email
    email&.downcase!
  end

  def downcase_nickname
    nickname&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'you shall not pass'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[destroy edit hide update]
  before_action :set_question_for_current_user, only: %i[destroy edit hide update]

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)

    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'your question is created'
    else
      flash.now[:alert] = 'data invalid'

      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'your question is updated'
    else
      flash.now[:alert] = 'data invalid'

      render :edit
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'your question is deleted'
  end

  def hide
    @question.toggle!(:hidden)

    redirect_to questions_path
  end

  def search
    @hashtag = Hashtag.question_hashtags_only.find_by!(name: params[:hashtag])
    @questions = @hashtag.questions.includes(%i[user author])
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.includes(%i[user author]).order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
    @hashtags = Hashtag.question_hashtags_only
  end

  def new
    @user = User.find_by!(nickname: params[:nickname])
    @question = Question.new(user: @user)
  end

  def edit; end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    session_params = params.require(:session)

    user = User.find_by(email: session_params[:email])&.authenticate(session_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'you signed in'
    else
      flash.now[:alert] = 'wrong email or password'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'you signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[destroy edit show update]
  before_action :authorize_user, only: %i[destroy edit update]

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: 'you signed up successfully'
    else
      flash.now[:alert] = 'data invalid'

      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit; end

  def show
    @questions = @user.questions.includes([:author]).order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'your data is updated'
    else
      flash.now[:alert] = 'data invalid'

      render :edit
    end
  end

  def destroy
    @user.destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'your account was deleted'
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation,
                                 :navbar_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, many)
    return one if count == 1

    many
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def link_hashtags(text)
    text.gsub(Hashtag::REGEXP) do |hashtag|
      link_to hashtag, search_questions_path(hashtag: hashtag.downcase.delete('#'))
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="background-color: 
        <%= current_user&.navbar_color || '#370617' %>;">
        <p class="title-sm text-bold"><%= link_to 'ask.me', root_path %></p>
        <div>
          <% if current_user.present? %>
            <span class="mr-sm">
              <%= link_to display_nickname(current_user), user_path(current_user) %>
            </span>
            <%= button_to 'Sign out', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign up', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Sign in', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>
      <% if flash[:notice].present? %>
        <p class="mt mb message message-notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert].present? %>
        <p class="mt mb message message-alert"><%= flash[:alert] %></p>
      <% end %>
      
      <%= yield %>
    </div>  
  </body>
</html>

app/views/questions/_form.html.erb
<div class="mt">
  <% question.errors.full_messages.each do |message| %>
    <p class="mb-sm text-red"><%= message %></p>
  <% end %>
</div>

<%= form_with model: question, data: { turbo: false } do |form| %>
  <%= form.hidden_field :user_id %>

  <p class="mt"><%= form.label :body, 'Question' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p class="mt">
    <%= form.submit 'Submit', class: 'button button-main' %> or <%= link_to 'return', :back %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<div class="text-grey text-sm mb">
  Question <%= link_to "##{question.id}", question_path(question) %>:
  <% author = question.author.present? ?
                (link_to display_nickname(question.author), user_path(question.author)) :
                'anonymous user' %>
  <%= author %> asked
  <%= link_to display_nickname(question.user), user_path(question.user) %>
</div>

<div class="mb-sm">
  <%= simple_format h(link_hashtags(question.body).html_safe) %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= simple_format h(link_hashtags(question.answer).html_safe) %>
  </div>
<% end %>

<div class="question-footer text-sm">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = question.answer.present? ? 'pencil' : 'reply' %>
      <% edit_title = question.answer.present? ? 'Edit' : 'Answer' %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question),
                  title: "#{edit_title} this question", class: 'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question), method: :delete,
                    title: 'Delete this question', data: { turbo_confirm: 'Are you sure?' },
                    class: 'mr-sm' %>
      <% eye_icon = question.hidden? ? 'eye' : 'eye-slash' %>
      <%= button_to fa_icon(eye_icon), hide_question_path(question), method: :put %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg">Edit the question</h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Recently joined us
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<div class="container mt">
  <h1 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'question', 'questions') %>
  </h1>
</div>

<% @questions.each do |question| %>
  <div class="container mt-sm <%= 'translucent' if question.hidden? %>">
    <%= render question %>
  </div>
<% end %>

<% if @hashtags.any? %>
  <div class="container mt">
    <p class="title-sm mb">Hashtags</p>
    <% @hashtags.each do |hashtag| %>
      <span><%= link_to hashtag.name, search_questions_path(hashtag: hashtag.name) %></span>
    <% end %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Create new question</h2>
  <p class="mb">for <%= link_to display_nickname(@user), user_path(@user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/search.html.erb
<div class="container mt">
  <h1 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'question', 'questions') %>
    with hashtag #<%= @hashtag.name %>
  </h1>
</div>

<% @questions.each do |question| %>
  <div class="container mt-sm <%= 'translucent' if question.hidden? %>">
    <%= render question %>
  </div>
<% end %>

app/views/questions/show.html.erb
<div class="container">
  <p class="mt"><%= render @question %></p>

  <p class="mt"><%= link_to 'Main page', questions_path %></p>
</div>

app/views/users/_no_questions.html.erb
<div class="container text-center mt-sm">
  <p class="title-sm text-grey">
    <%= display_nickname(@user) %> has not been asked any questions yet.
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  Be the first <%= link_to 'to ask!', new_question_path(nickname: @user) %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: display_nickname(user), class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title-lg">Update your profile</h2>

  <div class="mt">
    <% @user.errors.full_messages.each do |message| %>
      <p class="mb-sm text-red"><%= message %></p>
    <% end %>
  </div>

  <div class="mt">
    <p>
      <%= image_tag @user.gravatar_url, title: display_nickname(@user), class: 'rounded' %>
    </p>
    <p class="text-sm">
      If you want to change your avatar, register on
      <%= link_to 'Gravatar', 'https://gravatar.com', target: '_blank' %>
      and load your photo there.
    </p>
  </div>

  <div class="mt-lg">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Your name' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Your nickname' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt text-sm">
        If you don't want to change your password, leave fields below empty.
      </p>

      <p class="mt-sm"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :navbar_color %></p>
      <p><%= form.color_field :navbar_color, class: 'color-field' %></p>

      <p class="mt-lg">
        <%= form.submit 'Update', class: 'button button-main' %> /
        <%= link_to 'return', :back %>
      </p>
    <% end %>
  </div>

  <div class="mt">
    <%= button_to 'Delete my account', user_path(@user), method: :delete,
                  data: { turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title-lg">Join us and ask your questions</h2>

  <div class="mt">
    <% @user.errors.full_messages.each do |message| %>
      <p class="mb-sm text-red"><%= message %></p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Your name' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Your nickname' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email, 'Your email' %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit 'Sign up', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <p class="mt">
    <%= render partial: 'user_avatar', locals: {user: @user} %>
  </p>

  <% if current_user == @user %>
    <p class="mt mb-lg"><%= link_to fa_icon('pencil'), edit_user_path(@user) %></p>
  <% end %>
  <p class="text-bold mt mb-lg"><%= display_nickname(@user) %></p>
</div>

<% if @questions.count.zero? %>
  <%= render 'no_questions', user: @user %>
<% else %>
  <div class="container">
    <%= link_to 'Ask me', new_question_path(nickname: @user),
                class: 'button button-yellow' %>

    <p><%= render 'questions/form', question: @question %></p>
  </div>

  <div class="container mt">
    <h1 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'question', 'questions') %>
    </h1>
  </div>

  <% @questions.each do |question| %>
    <div class="container mt-sm <%= 'translucent' if question.hidden? %>">
      <%= render question %>
    </div>
  <% end %>
<% end %>